# Generated by Django 5.0 on 2024-01-16 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_habit_dailyperformance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='current_streak',
        ),
    ]
